# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-14 01:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('abstract', models.TextField()),
                ('speakers', models.TextField()),
                ('tags', models.TextField()),
                ('session_type', models.CharField(max_length=200)),
                ('session_time', models.TimeField()),
                ('category', models.CharField(max_length=200)),
                ('room', models.CharField(max_length=200)),
                ('rooms', models.TextField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
            ],
        ),
    ]
