# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-14 01:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0004_speaker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speaker',
            name='blog_link',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='github_link',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='gravatar_url',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='linkedin_link',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='twitter_link',
            field=models.URLField(null=True),
        ),
    ]
