# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-14 01:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0005_auto_20161214_0135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='speakers',
        ),
        migrations.AddField(
            model_name='meeting',
            name='speakers',
            field=models.ManyToManyField(to='meetings.Speaker'),
        ),
    ]
