# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-14 02:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0008_auto_20161214_0205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='meetings.Category'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='session_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='meetings.SessionType'),
        ),
    ]
