# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-15 00:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0009_auto_20161214_0206'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meeting',
            old_name='end_time',
            new_name='end_datetime',
        ),
        migrations.RenameField(
            model_name='meeting',
            old_name='start_time',
            new_name='start_datetime',
        ),
    ]
