# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-15 00:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0010_auto_20161215_0012'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='end_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='start_time',
            field=models.TimeField(null=True),
        ),
    ]
