# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-16 02:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0012_auto_20161216_0220'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='active',
            field=models.BooleanField(default=True, unique=True),
            preserve_default=False,
        ),
    ]
